# Generated by Django 4.1.1 on 2022-12-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
